Fixes #122
hazelcast/imdg-docs pull request #128
Opened 2021-03-10 11:31 UTC by Serdaro

2021-03-10 12:28 UTC, Holmistr requested changes
I would suggest adding an example to make it really clear.

2021-03-10 12:28 UTC, Holmistr commented on docs/modules/sql/pages/select-statement.adoc
> +WARNING: Note that, you must add indexes to the map objects to be queried and sorted.
I think we could be even clearer with an example:


WARNING: Note that, you must add sorted indexes to the map object's fields sorted by. For example, suppose you have a query like `SELECT * FROM persons ORDER BY name ASC`, there's has to be a sorted index on the `name` field like:
```
hazelcast:
  map:
    default:
      indexes:
        - type: SORTED
            attributes:
              - "name"
```

Please, verify with @petrpleshachkov that it has to be a sorted index, not just hash. But in general, I would add a specific example as it's much easier to understand.

2021-03-10 12:29 UTC, Holmistr commented on docs/modules/sql/pages/select-statement.adoc
> +WARNING: Note that, you must add indexes to the map objects to be queried and sorted.
Preferably, the configuration should be present in XML, YAML and programmatic configuration.

2021-03-10 15:21 UTC, Serdaro commented
@Holmistr , please see the latest commit in this PR for the improved WARNING.

2021-03-11 08:45 UTC, Holmistr approved these changes

2021-03-11 08:46 UTC, merged